api:
  dashboard: true

entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
    # Redirection du traffic http vers https auto
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    exposedBydefault: false
    endpoint: "unix:///var/run/docker.sock"
    # connexion au socket docker par défaut, permet de détecter tout les conteneurs d'un coup
    network: traefik-network

file:
  directory: /etc/traefik/dynamic
  watch: true
  # Emplacement des fichier de conf + watch true = hot reload

certificatesResolvers:
  letsencrypt:
    acme:
      email: vortextcg.aws@gmail.com
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
        # Test que l'on possède bien le domaine via le port 80

log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
