services:
  traefik:
    image: traefik:v3.4
    networks:
      - traefik-network

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../certs:/certs:ro
      - ../traefik/dynamic:/dynamic:ro
      - ./letsencrypt:/letsencrypt

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/tls.yml"

      # Providers - Swarm Provider pour Traefik v3
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      # Comment for now to check if network is the issue
      # - "--providers.swarm.network=traefik-network"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

      - "--certificatesresolvers.le.acme.email=vortex-tcg.aws@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

    env_file:
      - .env

    labels:
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_PASSWORD}"

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.vortex-tcg.online`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=le"
        - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
        - "traefik.http.services.vortex-traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s

  auth:
    image: vortextcg/vortex_repository:auth
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Host(`auth.vortex-tcg.online`)"
        - "traefik.http.routers.auth.entrypoints=websecure"
        - "traefik.http.routers.auth.tls=true"
        - "traefik.http.routers.auth.tls.certresolver=le"
        - "traefik.http.services.auth.loadbalancer.server.port=${AUTH_INTERNAL_PORT}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

  game:
    image: vortextcg/vortex_repository:game
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.game.rule=Host(`game.vortex-tcg.online`)"
        - "traefik.http.routers.game.entrypoints=websecure"
        - "traefik.http.routers.game.tls=true"
        - "traefik.http.routers.game.tls.certresolver=le"
        - "traefik.http.services.game.loadbalancer.server.port=${GAME_INTERNAL_PORT}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 512M

  api:
    image: vortextcg/vortex_repository:api
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.vortex-tcg.online`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.tls.certresolver=le"
        - "traefik.http.services.api.loadbalancer.server.port=${API_INTERNAL_PORT}"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M

networks:
  traefik-network:
    driver: overlay
    attachable: true
