services:
  traefik:
    image: traefik:v3.4
    networks:
      - traefik-network

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/www/vortex_tcg/certs:/certs:ro
      - /var/www/vortex_tcg/traefik/dynamic:/dynamic:ro
      - /var/www/vortex_tcg/server/letsencrypt:/letsencrypt
    extra_hosts:
      - "host.docker.internal:host-gateway"

    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.file.filename=/dynamic/tls.yml"
      - "--providers.swarm=true"
      - "--providers.swarm.exposedbydefault=false"
      - "--providers.swarm.network=traefik-network"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.file.directory=/dynamic"
      - "--providers.file.watch=true"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--certificatesresolvers.le.acme.email=vortex-tcg.aws@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--serversTransport.insecureSkipVerify=true"

    env_file:
      - .env

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.vortex-tcg.online`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.routers.dashboard.tls.certresolver=le"
        - "traefik.http.services.vortex-traefik.loadbalancer.server.port=8080"
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s

  auth:
    image: vortextcg/vortex_repository:auth
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.auth.rule=Host(`auth.vortex-tcg.online`)"
        - "traefik.http.routers.auth.entrypoints=websecure"
        - "traefik.http.routers.auth.tls=true"
        - "traefik.http.routers.auth.tls.certresolver=le"
        - "traefik.http.services.auth.loadbalancer.server.port=5238"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

  game:
    image: vortextcg/vortex_repository:game
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.game.rule=Host(`game.vortex-tcg.online`)"
        - "traefik.http.routers.game.entrypoints=websecure"
        - "traefik.http.routers.game.tls=true"
        - "traefik.http.routers.game.tls.certresolver=le"
        - "traefik.http.services.game.loadbalancer.server.port=8000"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M

  api:
    image: vortextcg/vortex_repository:api
    networks:
      - traefik-network
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.vortex-tcg.online`)"
        - "traefik.http.routers.api.entrypoints=websecure"
        - "traefik.http.routers.api.tls=true"
        - "traefik.http.routers.api.tls.certresolver=le"
        - "traefik.http.services.api.loadbalancer.server.port=5238"
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 128M

  sonarqube:
    image: sonarqube:community
    networks:
      - traefik-network
    env_file:
      - sonar.env
    environment:
      - SONAR_WEB_JAVAADDITIONALOPTS=-Xmx512m -Xms128m
      - SONAR_CE_JAVAADDITIONALOPTS=-Xmx256m -Xms128m
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Xmx256m -Xms256m -XX:MaxDirectMemorySize=128m
    volumes:
      - /var/sonarqube/data:/opt/sonarqube/data
      - /var/sonarqube/logs:/opt/sonarqube/logs
      - /var/sonarqube/extensions:/opt/sonarqube/extensions
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarqube.rule=Host(`sonarqube.vortex-tcg.online`)"
        - "traefik.http.routers.sonarqube.entrypoints=websecure"
        - "traefik.http.routers.sonarqube.tls=true"
        - "traefik.http.routers.sonarqube.tls.certresolver=le"
        - "traefik.http.services.sonarqube.loadbalancer.server.port=9000"
        - "traefik.http.services.sonarqube.loadbalancer.responseforwarding.flushinterval=100ms"
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 2500M
        reservations:
          memory: 1800M

  sonarqube-db:
    image: postgres:15
    networks:
      - traefik-network
    env_file:
      - sonar.env
    volumes:
      - /var/sonarqube/postgresql/data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  traefik-network:
    driver: overlay
    attachable: true
