services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/:/etc/traefik:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./acme:/acme
      - ./logs:/var/log/traefik
    environment:
      - TZ=Europe/Paris # Pour avoir les bonnes heures des logs

  migrations:
    image: vortextcg/vortex_repository:migrations
    pull_policy: always
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  auth:
    image: vortextcg/vortex_repository:auth
    pull_policy: always
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.vortex-tcg.online`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls=true"
      - "traefik.http.routers.auth.tls.certresolver=letsencrypt"
      - "traefik.http.services.auth.loadbalancer.server.port=${AUTH_INTERNAL_PORT}"
    env_file:
      - .env
    depends_on:
      migrations:
        condition: service_completed_successfully

  game:
    image: vortextcg/vortex_repository:game
    pull_policy: always
    labels:
      - "traefik.enable=true"
    env_file:
      - .env
    ports:
      - "${GAME_PORT}:${GAME_INTERNAL_PORT}"
    depends_on:
      migrations:
        condition: service_completed_successfully

  api:
    image: vortextcg/vortex_repository:api
    pull_policy: always
    labels:
      - "traefik.enable=true"
    env_file:
      - .env
    ports:
      - "${API_PORT}:${API_INTERNAL_PORT}"
    depends_on:
      migrations:
        condition: service_completed_successfully

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
