@auth_HostAddress = http://localhost:5001

### Test login avec identifiants corrects
POST {{auth_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password123"
}

### Test login avec identifiants incorrects
POST {{auth_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "wrong@example.com",
  "password": "wrongpass"
}
