name: Get secrets
on: [workflow_dispatch]

jobs:
  connect-to-vault:
    runs-on: ubuntu-latest
    steps:
      - name: Get secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            aws/data/EC2_HOST | EC2_HOST

      - name: try to connect EC2
        run: |
          # 1. Install vault CLI if not available
          apt-get install -y vault

          # 2. Generate temp SSH keypair
          ssh-keygen -t rsa -f /tmp/pipeline_key -N ""

          # 3. Sign the public key with Vault
          vault write -field=signed_key ssh/sign/pipeline-role public_key=@/tmp/pipeline_key.pub > /tmp/pipeline_key-cert.pub

          # 4. Try to SSH into the EC2
          ssh -o StrictHostKeyChecking=no -i /tmp/pipeline_key -i /tmp/pipeline_key-cert.pub ubuntu@$EC2_HOST "echo 'SSH works!'"
