name: Get secrets
on: [workflow_dispatch]

jobs:
  connect-to-vault:
    runs-on: self-hosted
    steps:
      - name: Get Vault secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://localhost:8200
          method: token
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            secret/aws EC2_HOST | EC2_HOST
            secret/aws EC2_USER | EC2_USER
